# Generated by Django 5.0 on 2023-12-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('phone_no', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=300)),
            ],
        ),
    ]
